apiVersion: batch/v1
kind: Job
metadata:
  generateName: sample-job-
  namespace: test-slurm
  labels:
    kueue.x-k8s.io/queue-name: user-queue
  annotations:
    slurmjob.slinky.slurm.net/account: slurm
    slurmjob.slinky.slurm.net/partition: "all"
spec:
  parallelism: 1
  completions: 1
  suspend: true
  template:
    metadata:
      annotations:
        slurmjob.slinky.slurm.net/account: slurm
        slurmjob.slinky.slurm.net/partition: all
    spec:
      containers:
      - name: dummy-job
        image: quay.io/prometheus/busybox
        command: [sh, -c, sleep 500]
      restartPolicy: Never

