apiVersion: batch/v1
kind: Job
metadata:
  generateName: sample-job-
  namespace: slinky
  labels:
    kueue.x-k8s.io/queue-name: user-queue
  annotations:
    slinky.slurm.net/job-name: job-sleep-single-3
    slurmjob.slinky.slurm.net/account: slurm
    slurmjob.slinky.slurm.net/partition: all
spec:
  parallelism: 3
  completions: 3
  suspend: true
  template:
    metadata:
      annotations:
        slinky.slurm.net/job-name: job-sleep-single-3
        slurmjob.slinky.slurm.net/account: slurm
        slurmjob.slinky.slurm.net/timelimit: "10"
        slurmjob.slinky.slurm.net/partition: all
    spec:
      schedulerName: slurm-bridge-scheduler
      containers:
      - name: dummy-job
        image: quay.io/prometheus/busybox
        command: [sh, -c, sleep 30]
        resources:
          requests:
            cpu: "1"
            memory: "100Mi"
      restartPolicy: Never

