apiVersion: trainer.kubeflow.org/v1alpha1
kind: ClusterTrainingRuntime
metadata:
  name: torch-slurm
  labels:
    trainer.kubeflow.org/framework: torch
spec:
  mlPolicy:
    numNodes: 1
    torch: {}
  template:
    spec:
      replicatedJobs:
        - name: node
          template:
            metadata:
              labels:
                trainer.kubeflow.org/trainjob-ancestor-step: trainer
              annotations:
                slinky.slurm.net/job-name: job-sleep-minow
                slurmjob.slinky.slurm.net/account: slurm
                slurmjob.slinky.slurm.net/partition: all
                slurmjob.slinky.slurm.net/timelimit: "1"
            spec:
              template:
                spec:
                  containers:
                    - name: node
                      image: pytorch/pytorch:2.10.0-cuda12.8-cudnn9-runtime
